[profile.default]
src = "contracts/onchain/src"
test = "contracts/onchain/test"
script = "contracts/onchain/script"
out = "contracts/onchain/out"
cache_path = "contracts/onchain/cache"
libs = ["/Users/najnomics/november/NOSA/EigenDark-Hook/contracts/onchain/node_modules", "lib"]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{ access = "read-write", path = "contracts/onchain/.forge-snapshots/" }]
solc_version = "0.8.30"
via_ir = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

